logging:
  level:
    org.springframework.web: '${LOG_LEVEL:INFO}'
    com.snipe.CallHandling: '${LOG_LEVEL:INFO}'
    
spring:
  application:
    name: 'CallHandling'  
server:    
  port: '${SERVER_PORT:8081}'
  contextPath: '/CallHandling'
     
datasource:  
  snipe:
    CallHandling: 
      driverClassName: '${DRIVER_CLASS:org.postgresql.Driver}'
      url: '${JDBC_URL:jdbc:postgresql://localhost:5432/callhandling}'
      username: '${DB_USER_NAME:postgres}'
      password: '${DB_USER_PASSWORD:test}'
       

 
